import type { Metadata } from "next";
import "./globals.css";
import { DotPattern } from "@/components/magicui/dot-pattern";
import { cn } from "../lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Cloud With Anne Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gray-50 bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px]`}
      >
        <Navbar />
        <DotPattern className={cn("[mask-image:radial-gradient(300px_circle_at_center,white,transparent)]",)}/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
